// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBuYoN7BlTBwure1Dg4XHwaGVnTBsZXKE',
    appId: '1:632906255877:android:1326397c8ad17967b3166c',
    messagingSenderId: '632906255877',
    projectId: 'my-task-manager-app-2dcaa',
    storageBucket: 'my-task-manager-app-2dcaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcuL1K4xGKtIc1OpC3c1FTtA-wJU-N4Vs',
    appId: '1:632906255877:ios:e5672973fc4b38b5b3166c',
    messagingSenderId: '632906255877',
    projectId: 'my-task-manager-app-2dcaa',
    storageBucket: 'my-task-manager-app-2dcaa.firebasestorage.app',
    iosClientId: '632906255877-mv9ier3n4c89qdfg6un4q70o37c1dmka.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

}